### ISSUE TITLE
Substratus should work out of the box in a newly minted GCP project

### ISSUE THREAD

**Issue by nstogner** [substratusai/substratus#10]
Tracking some issues here, for a fresh project, outside of an org (no cascading permissions).

I had to add myself as a Storage Admin to list buckets (needed by terraform - when I added a bucket to be used with GCS fuse).

<img width="674" alt="Screenshot 2023-06-20 at 7 56 28 PM" src="https://github.com/substratusai/substratus/assets/10274189/5a1944fc-4eaa-46e3-9718-23d175fcbd92">

**Comment by brandonjbjelland** [comment]
Not able to reproduce this as a project owner in our org. Closing unless we see others facing the issue.
