### ISSUE TITLE
Consolidate Substratus Image Repos

### ISSUE THREAD

**Issue by nstogner** [substratusai/substratus#106]
Proposal: Consolidate all Substratus image repos for easier maintenance and easier search for users.

NOTE: In this implementation, perhaps the base-images are used for Models, Datasets, and Notebooks, and they contain `notebook.sh` script along with Jupyter pre-installed. This removes the need for a separate notebook image repo.

`base-images.git`:

```
  ubuntu/*    # Image: substratusai/os-ubuntu
  ...
```

`dataset-images.git`:
```
  squad/*     # Image: substratusai/dataset-squad
  ...
```

`model-loader-images.git`:
```
  huggingface/* # Image: substratusai/model-loader-huggingface
  ...
```

`model-trainer-images.git`:
```
  huggingface/* # Image: substratusai/model-trainer-huggingface
  ...
```

`server-images.git`:
```
  basaran/*   # Image: substratusai/server-basaran
  ...
```

[Path based triggers](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) could be used to filter Github actions build jobs. For example, when building the facon-7b model:

```yaml
on:
  push:
    paths:
      - 'models/falcon-7b/*'
      - 'base/ubuntu/*'
```

**Comment by nstogner** [comment]
Alternative:

`os-images.git`:

```
  ubuntu/*    # Image: substratusai/os-ubuntu
  ...
```

`dataset-images.git`:
```
  squad/*     # Image: substratusai/dataset-squad
  ...
```

`model-loader-images.git`:
```
  huggingface/* # Image: substratusai/model-loader-huggingface
  ...
```

`model-trainer-images.git`:
```
  huggingface/* # Image: substratusai/model-trainer-huggingface
  ...
```

`notebook-images.git`:
```
  default/*   # Image: substratusai/notebook-default
  ...
```

`server-images.git`:
```
  basaran/*   # Image: substratusai/server-basaran
  ...
```

**Comment by nstogner** [comment]
See the following implementations of consolidated repos:

https://github.com/substratusai/base-images
https://github.com/substratusai/model-loader-images

If we like this direction, we can add to it, otherwise, we can remove.

**Comment by brandonjbjelland** [comment]
@samos123 and I discussed this for a few minutes and reached consensus on a monorepo including base images. Rationale:

1. This is a reversible decision - we just need to decide and commit.
2. monorepos are a good optimization for speed (reduce context switching and duplication) especially early on. [Support here](https://matt-rickard.com/monorepos).
3. It's contributor friendly - if a community member wants to add a model loader, dataset loader, or even has their own category of image that we hadn't thought of (model evaluator, quantizer, dataset generator, widget producer) the image monorepo is a natural place for even odd use cases (for now at least - there's a reasonably good case further down the road for community vs substratus supported images).
4. build and testing becomes simpler when you have a single set of actions to work against. It's just easier to know that everything is working together as a unit when it ships together
5. limit or eliminates cross-repo references/indirection - answering the question "how did this base image get built?" is something a passerby can readily understand in a monorepo

**Comment by brandonjbjelland** [comment]
The implementation I have in mind:
1. a repo named `[image-builders](https://github.com/substratusai/image-builders)` - unsure if we want to split early and call this official-image-builders or supported-image-builders, contrasting it with community-image-builders
2. a path structure like you suggested only with a base dir reflecting purpose:
  ```
  bases/ubuntu/*    # Image: substratusai/os-ubuntu
  servers/basaran/*   # Image: substratusai/server-basaran
  model-loaders/huggingface-model-loader/* # Image: substratusai/model-loader-huggingface
  model-trainers/huggingface-model-trainer/* # Image: substratusai/model-trainer-huggingface
  dataset-loaders/.gitkeep # none exist yet but we should have one for retrieving and packaging a huggingface dataset. I think this would be valuable where datasets require a hf token. Perhaps more generally, a dataset fetcher that simply pulls from any https/ssh source.
  ```

Another server emerges when we have santacoder and starcoder working and fine-tuned. Those servers need to implement the [language server protocol](https://microsoft.github.io/language-server-protocol/) spec to be used by lsp clients. Likewise, the [text-generation-inference](https://github.com/huggingface/text-generation-inference) would make for a worthwhile server effort.

**Comment by samos123** [comment]
I rather keep it simple without nested directories for container image directories:
```
substratus-images:
  base (helpful for HF loader which doesn't need many dependencies and keeps image small)
  base-gpu (maybe this is our only base)
  model-loader-huggingface # image substratusai/model-loader-huggingface
  model-trainer-huggingface
  dataset-loader-k8s-instruct
  dataset-loader-squad
```

Every directory under substratus-images should be a directory with a Dockerfile. By convention, the resulting image will be substratusai/{DIRECTORY_NAME}. 

What you all think?

**Comment by brandonjbjelland** [comment]
☝️  That's perfectly good by me.

**Comment by nstogner** [comment]
I am good with the monorepo, I would name it `github.com/substratusai/images.git`. I prefer to use a single base image for gpu and non-gpu workloads. This might actually help speed things up b/c of base layer caching.

**Comment by nstogner** [comment]
Started on this instead of updating other repos in place

**Comment by nstogner** [comment]
NOTE: images.git is currently dependent upon https://github.com/substratusai/substratus/pull/109
