### ISSUE TITLE
Handle PromptTemplates for training and inferencing

### ISSUE THREAD

**Issue by samos123** [substratusai/substratus#133]
The finetuning only needs a single field "text" that contains the prompt + completion combined into a single text field. This allows the Dataset resource to be responsible for ensuring there is a field that contains the data that can be used by finetuning. Right now the trainer hardcodes the way prompt and completion get combined, but that won't fit all LLM use cases.

Many popular datasets already come with a column that has the combined text. Take a look for example at the Alpaca dataset: https://huggingface.co/datasets/tatsu-lab/alpaca

Proposed changes
- (Current roadmap) Model.params.prompt_template will be used to capture the prompt template to override whatever the default is of the image in use. An trainer image is expected to come with a default prompt template.
- (Backlog) Introduce a new dataset type `Text` in addition to `PromptCompletion`
- (Backlog) Trainer will do the following based on Dataset type
-- Text: Choose one the fields of the dataset (default: text) overridable by setting params.dataset_text_field
-- PromptCompletion: Have a built-in default prompt template like it is right now and also allow users to override the prompt template
- (Backlog) Controller: Add new Dataset type and pass the Dataset type to the trainer

Example in Model using trainer image:
```
params:
  dataset_text_field: content
```

^ To override the default `dataset_text_field: text`

**Comment by nstogner** [comment]
`overridable by setting params.dataset_text_field` --> Why should this be over-ridable? IMO datasets types should have hard-contracts:

`type: Text` --> `{"text": "..."}`
`type: PromptCompletion` --> `{"prompt": "...", "completion": "..."}`

If we allow for variability, then users cannot simply plug-n-play datasets with model trainers.

**Comment by nstogner** [comment]
NOTE: The Server type will likely need a prompt template for inference. It would be nice if it could be sourced from the referenced `.spec.model` and pulled from that Model's `.spec.params.prompt_template`.
