### ISSUE TITLE
Issue when installing v0.6.5-alpha

### ISSUE THREAD

**Issue by samos123** [substratusai/substratus#134]
Steps to reproduce:
```
docker pull substratusai/installer:latest
docker run -it \                         
  -v ${HOME}/.kube:/root/.kube \
  -e PROJECT=$(gcloud config get project) \
  -e TOKEN=$(gcloud auth print-access-token) \
  substratusai/installer gcp-down.sh
docker run -it \                         
  -v ${HOME}/.kube:/root/.kube \
  -e PROJECT=$(gcloud config get project) \
  -e TOKEN=$(gcloud auth print-access-token) \
  substratusai/installer gcp-up.sh
```

```
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to google_service_account.notebook, provider "provider[\"registry.terraform.io/hashicorp/google\"]"
│ produced an unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

```

**Comment by samos123** [comment]
@brandonjbjelland could use your terraform expertise with this one.

After I reran gcp-up.sh
```
Error: Error creating service account: googleapi: Error 409: Service account substratus-notebook already exists within project
```

**Comment by brandonjbjelland** [comment]
Hmmm I don't think the TF resource name changed in recent PRs... That could cause this. Quick way out: delete the sa in GCP. Tf will recreate it next apply w proper role bindings.

**Comment by samos123** [comment]
That didn't seem to do the trick. I deleted the SA and ran gcp-down.sh but it keeps causing this issue.

**Comment by samos123** [comment]
@brandonjbjelland is unable to reproduce so probably something special in my environment since I can reliably reproduce this issue when doing a gcp-down.sh and then gcp-up.sh

**Comment by brandonjbjelland** [comment]
Running through an install from a just-created project and everything seems smooth so far. The falcon7b model, server, and dataset are all working as expected.

**Comment by brandonjbjelland** [comment]
Closing this. I think the datapoint is important as I've hit similar with terraform. If we see things like this reoccurring, we should at the very least have a doc on how folks can get out.
