### ISSUE TITLE
Feature Request: Notebook support constant file sync

### ISSUE THREAD

**Issue by samos123** [substratusai/substratus#140]
Projects like ksync can be considered to implement constant filesysnc instead of current mechanism where sync only happens during initial creation and once you hit Ctrl + C. Ksync itself probably can't be used as-is but the same mechanism should work.

Issues with current approach:
* If the pod gets deleted for some reason it will cause you to lose all your modifications
* Unable to view the changes in real-time in your local notebook viewer (e.g. vscode)

**Comment by nstogner** [comment]
Some options on first glance:

Ksync which builds upon [syncthing](https://docs.syncthing.net/) appears to have a pretty complicated [architecture](https://ksync.github.io/ksync/docs/architecture.html).

Looked for inspiration in [skaffold syncing](https://skaffold.dev/docs/filesync/), but it appears to tackle local machine to Pod syncing, which is a different use case and simpler than Pod to localhost.

**Comment by nstogner** [comment]
Started work on this... Writing a custom solution for our use-case.
