### ISSUE TITLE
Provide GCS URL once model is created instead of once ready

### ISSUE THREAD

**Issue by samos123** [substratusai/substratus#144]
Right now the GCS url is only provided once the model is ready, however it would be nice to be able to pull down the logs as the model is being loaded/trained. So hoping that if we provide the URL I can pull down logs directly while it's loading.

**Comment by nstogner** [comment]
This sounds like a good idea. Also: I think we should consider a helper CLI command for doing this.

**Comment by samos123** [comment]
I verified that if you had some way to continiously sync /content/logs/load.ipynb then you could view the process in real-time. This would work with both VScode or by e.g. having a server built-in  views the notebooks under logs in read-only mode.
