### ISSUE TITLE
Local kind cluster installation

### ISSUE THREAD

**Issue by d3287t328** [substratusai/substratus#152]
I would like to install the project in a kind cluster for local testing.

**Comment by samos123** [comment]
This won't be a straight forward in current code base so suggest splitting this up into the following issues:
* Allow specify GPU count only without GPU type
* Make the container image registry configurable
* Provide built-in cluster persistent storage for Model and Dataset

I can take a stab at filing the issues with how we're envisioning local dev should work

**Comment by nstogner** [comment]
@d3287t328 Taking this on. Should have support for `kind` soon if all goes well.
