### ISSUE TITLE
implement readiness probe on servers

### ISSUE THREAD

**Issue by brandonjbjelland** [substratusai/substratus#153]
During the execution of our documentation tests, we have noticed that we have to wait ~30 seconds before we are able to create a port forward to the pods of Servers. This delay appears to be caused by the fact that the application inside the pod isn't immediately ready to accept connections on port 8080.

We currently specify readiness probes on Notebooks but not on Servers.

**Comment by nstogner** [comment]
Agreed, Servers are missing some {best-practices}.
