### ISSUE TITLE
System tests currently test the previous commit's images

### ISSUE THREAD

**Issue by nstogner** [substratusai/substratus#208]
System tests reference images with the `:main` tag. They run on the main branch after merges occur. However, they do not run after the docker-build-push steps, so they end up testing the images from the previous commit to `main`.

![Screenshot 2023-08-21 at 8 59 19 PM](https://github.com/substratusai/substratus/assets/10274189/cac914b4-2060-400a-82e6-6f355ae6f4ce)

**Comment by samos123** [comment]
I fixed this by having system tests build the image from current revision and use it for the system tests
