### ISSUE TITLE
New kubectl plugin for creating notebooks from sources

### ISSUE THREAD

**Issue by nstogner** [substratusai/substratus#23]
```sh
kubectl create notebook --from dir://<dir>
kubectl create notebook --from model://<name>
kubectl create notebook --from git://<url>
```

PS: Is it possible to create a kubectl plugin that extends a standard kubectl subcommand (i.e. `kubectl create`)?

**Comment by brandonjbjelland** [comment]
Cast this aside as done but reconsidering. I think this task should change to align with the notebook design falling out of the PR here: https://github.com/substratusai/substratus/pull/75/files#diff-b0929dacd4f1fc192cd308c1a9db2e85154ea742ccec315518e659d7f6a3efc7

**Comment by brandonjbjelland** [comment]
Resolved by: https://github.com/substratusai/substratus/pull/147
