### ISSUE TITLE
Default Model and Dataset Dockerfiles

### ISSUE THREAD

**Issue by nstogner** [substratusai/substratus#60]
If might be possible to specify a system-level default Dockerfile for Model and another for Datasets.

This Dockerfile could be sourced `FROM` a standard base Dockerfile which provides the `train.sh` / etc. scripts along with some pre-installed python packages like Jupyter Lab.

The default Dockerfiles would allow for users to spin up new Dataset loaders and Models with a very minimal set of files in their repo.

**Comment by brandonjbjelland** [comment]
Do we need these in our current design? Loader images for datasets and models have taken their place largely. We have a base image that notebooks can launch into which essentially are base images for model and dataset. Closing but reopen if you think this still hasn't been realized.
