### ISSUE TITLE
Publish base Substratus Dockerfiles

### ISSUE THREAD

**Issue by nstogner** [substratusai/substratus#61]
There could be a few base Substratus Dockerfiles that are published for Models and Datasets, with variations for different python versions (perhaps as tags).

These Dockerfiles might contain:

- cuda libraries
- standard scripts (i.e. `train.sh`, etc).
- Jupyter Labs pre-installed
- non-root directory permissions

**Comment by nstogner** [comment]
Started working on this: https://github.com/substratusai/base-images

NOTE: This should also help with build and load times since base images layers will be more consistent.

**Comment by brandonjbjelland** [comment]
This is done since we moved to the dedicated images repo 🥳
