### ISSUE TITLE
Publish container image for installer

### ISSUE THREAD

**Issue by nstogner** [substratusai/substratus#71]
See quickstart guide which references a pre-built docker image to reduce quickstart install steps: https://www.substratus.ai/docs/quickstart

**Comment by samos123** [comment]
are you thinking a prebuilt image that has all the tools minus the terraform resources?

**Comment by nstogner** [comment]
Thinking we can just publish the image as-is which come with the terraform in it. That way users do not need to even clone the repo to install substratus.
