### ISSUE TITLE
Allow Dataset to contain a set of files

### ISSUE THREAD

**Issue by brandonjbjelland** [substratusai/substratus#97]
## Summary

Currently our CRD for Dataset specifies the following:

```
type DatasetSpec struct {
	// Filename is the name of the file when it is downloaded.
	Filename string `json:"filename"`
	// ...
}
```

Looking closer at datasets on HF, many are split across many files (the [stack dedup](https://huggingface.co/datasets/bigcode/the-stack-dedup/tree/main), [the pile](https://huggingface.co/datasets/EleutherAI/pile/blob/main/pile.py#L34-L35) is a set of 22 files, image datasets). This seems reasonable for dataset organization purposes and avoiding huge files with heterogeneous content.

## Potential solutions

1. a list of Filenames
2. a single Filename but with the contents almost always stored as tar.gz - this would likely work on our current API
3. perhaps filename becomes something like `RootPath` or `Dir`
4. I'm looking closer at the codebase and wondering if we have a true need for Filename at all. Potentially we can remove it.

**Comment by nstogner** [comment]
Option 4 sounds good to me for now

**Comment by nstogner** [comment]
@samos123 Will need to update `model-trainer-huggingface` for option 4. It should just search for process all `/content/data/*.jsonl` files for now I think.

**Comment by nstogner** [comment]
@brandonjbjelland Did we agree on that ?

**Comment by brandonjbjelland** [comment]
Yes agreed @nstogner

**Comment by brandonjbjelland** [comment]
`Filename` has been dropped. We're flexible here now.
